# This file is a template, and might need editing before it works on your project.
# Full project: https://gitlab.com/pages/plain-html

stages:
- deploy

pages:
  stage: deploy
  script:
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
